name: NHL_AI_AGENT
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - xgboost
  - ipykernel
  - pip
  - pip:
      - hockey_rink
# NOTE: Specific package versions seem to make the searching faster? May want to investigate in future
